common/models/Template.php
<?php

namespace common\models;

use \common\models\base\BaseTemplate;
use yii\behaviors\TimestampBehavior;
use \common\models\ScriptTemplateAssignment;
use \common\models\TemplateImageAssignment;
use \common\models\UserTemplateAssignment;
use \common\models\SubscriptionUserAssignment;
use \common\models\Subscription;
use \common\models\Section;
use \common\models\Script;
use \backend\models\Mediafile;
use \backend\models\User;
use yii\helpers\ArrayHelper;


class Template extends BaseTemplate
{
    public $scriptIds = [];
    public $imageIds = [];
    public $previewImg = null;

    public $scripts = null;

    const TYPE_FREE = 'free';
    const TYPE_PAID = 'paid';

    public static $types = [
        self::TYPE_FREE => 'Free',
        self::TYPE_PAID => 'Paid',
    ];

    const STATUS_ACTIVE = 'active';
    const STATUS_DISABLED = 'disabled';

    /** @var array $dependencies uses to extend api response on view request */
    public $dependencies = ['scripts' => [], 'images' => []];
    /** @var array $sections uses to extend api response on view request */
    public $sections = [];

    public function fields()
    {
        return [
            'id',
            'title',
            'comment',
            'preview_img',
            'html',
            'css',
            'type',
            'dependencies',
            'sections'
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['id', 'created', 'modified'], 'integer'],
            [['html', 'css', 'type', 'status'], 'string'],
            [['title'], 'string', 'max' => 150],
            [['comment', 'preview_img'], 'string', 'max' => 255],
            [['scriptIds', 'imageIds'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Template title',
            'comment' => 'Comments',
            'preview_img' => 'Preview Image',
            'html' => 'HTML',
            'css' => 'CSS',
            'type' => 'Template type',
            'created' => 'Created',
            'modified' => 'Modified',
            'status' => 'Template status',
        ];
    }

    public function behaviors()
    {
        return [
            'dateTimeStampBehavior' => [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'modified',

            ]
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {

        /**
         * remove scripts dependencies
         */
        $assignments = ScriptTemplateAssignment::find()->where("template_id={$this->id}")->all();
        if ($assignments) {
            foreach ($assignments as $assignment) {
                $assignment->delete();
            }
        }

        /**
         * save scripts dependencies
         */
        if (!empty($this->scriptIds)) {
            $o = 0;
            $this->scriptIds = array_unique($this->scriptIds);
            foreach ($this->scriptIds as $id) {
                $r = new ScriptTemplateAssignment();
                $r->template_id = $this->id;
                $r->script_id = $id;
                $r->order = $o;
                $r->save();
                $o++;
            }
        }

        /**
         * remove images dependencies
         */
        $assignments = TemplateImageAssignment::find()->where("template_id={$this->id}")->all();
        if ($assignments) {
            foreach ($assignments as $assignment) {
                $assignment->delete();
            }
        }

        /**
         * save images dependencies
         */
        if (!empty($this->imageIds)) {
            $this->imageIds = array_unique($this->imageIds);
            foreach ($this->imageIds as $id) {
                $tia = new TemplateImageAssignment();
                $tia->template_id = $this->id;
                $tia->file_id = $id;
                $tia->save();
            }
        }

        parent::afterSave($insert, $changedAttributes);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getScriptTemplateAssignments()
    {
        return $this->hasMany(ScriptTemplateAssignment::className(), ['template_id' => 'id'])->orderBy('order');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTemplateImageAssignments()
    {
        return $this->hasMany(TemplateImageAssignment::className(), ['template_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSectionsAssigned()
    {
        return $this->hasMany(Section::className(), ['id' => 'section_id'])->viaTable('template_section_assignment', ['template_id' => 'id']);
    }

    public function getSectionsNumber()
    {
        return TemplateSectionAssignment::find()->where(['template_id' => $this->id])->count();
    }

    public function getUserTemplateAssignmentNumber()
    {
        return UserTemplateAssignment::find()->where(['template_id' => $this->id])->count();
    }

    public function getFilesAssigned()
    {
        return $this->hasMany(Mediafile::className(), ['id' => 'file_id'])->viaTable('template_image_assignment', ['template_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getScriptsAssigned()
    {
        return $this->hasMany(Script::className(), ['id' => 'script_id'])->viaTable('script_template_assignment', ['template_id' => 'id']);
    }

    public static function getUserAllowedTemplatesIds($userId)
    {
        $freeTemplates = self::getFreeTemplatesIds();
        $directlyAssignedTemplates = UserTemplateAssignment::getUserAssignedTemplatesIds($userId);

        $templatesFromSubscription = [];
        if ($userActiveSubscription = SubscriptionUserAssignment::getUserActiveSubscription($userId)) {
            if ($subscription = Subscription::find()->where(['id' => $userActiveSubscription->subscription_id])->one()) {
                $subscriptionTemplates = $subscription->subscriptionTemplateAssignments;
                if ($subscriptionTemplates) {
                    foreach ($templatesFromSubscription as $tfs) {
                        $templatesFromSubscription[] = $tfs->template_id;
                    }
                }
            }
        }

        $ids = array_merge($freeTemplates, $directlyAssignedTemplates, $templatesFromSubscription);
        return ArrayHelper::getColumn(Template::find()->where(['status' => Template::STATUS_ACTIVE, 'id' => $ids])->all(), 'id');
    }

    public function getUsersIdsAssignedToTemplate()
    {
        $users = [];

        $directlyAssignedUsers = $this->users;
        if ($directlyAssignedUsers) {
            foreach ($directlyAssignedUsers as $user) {
                $users[] = $user->id;
            }
        }

        $assignedViaSubscriptions = $this->userIdsThroughSubscription;

        $users = array_merge($users, $assignedViaSubscriptions);

        return array_unique($users);
    }

    public function getUserIdsThroughSubscription()
    {
        $usersIds = [];
        $subscriptions = $this->subscriptions;
        if ($subscriptions) {
            foreach ($subscriptions as $subscription) {
                $users = $subscription->users;
                if ($users) {
                    foreach ($users as $user) {
                        $usersIds[] = $user->id;
                    }
                }
            }
        }

        return $usersIds;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->viaTable('user_template_assignment', ['template_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubscriptions()
    {
        return $this->hasMany(Subscription::className(), ['id' => 'subscription_id'])->viaTable('subscription_template_assignment', ['template_id' => 'id']);
    }

    public static function getFreeTemplatesIds()
    {
        return self::find()->select('id')->where(['type' => self::TYPE_FREE, 'status' => self::STATUS_ACTIVE])->column();
    }

    public function getPreviewImageModel()
    {
        if ($this->preview_img && $previewImg = Mediafile::find()->where('id=:id', [':id' => $this->preview_img])->one()) {
            $this->previewImg = $previewImg;
        }

        return $this->previewImg;
    }

    public function fetchDependencies()
    {
        $this->dependencies['images'] = $this->filesAssigned;
        $this->dependencies['scripts'] = $this->scriptsAssigned;

        return $this->dependencies;
    }

    public function fetchSections()
    {
        $this->sections = $this->sectionsAssigned;
        if ($this->sections) {
            foreach ($this->sections as $key => $section) {
                if (is_numeric($section->preview_img)) {
                    $section->preview_img = $section->previewImageModel;
                    $section->fetchDependencies();
                }
            }
        }

        return $this->sections;
    }
}

backend/controllers/AdminController.php
<?php

namespace backend\controllers;

use common\models\Subscription;
use common\models\SubscriptionUserAssignment;
use Yii;
use yii\web\NotFoundHttpException;
use yii\helpers\ArrayHelper;
use common\models\Template;


class AdminController extends \amnah\yii2\user\controllers\AdminController
{

    /**
     * Display a single User model
     *
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if ($model)
            $model->templates = ArrayHelper::map(Template::find()->where(['status' => Template::STATUS_ACTIVE])->all(), 'id', 'title');

        return $this->render('view', [
            'user' => $model,
        ]);
    }

    /**
     * Create a new User model. If creation is successful, the browser will
     * be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        /** @var \amnah\yii2\user\models\User $user */
        /** @var \amnah\yii2\user\models\Profile $profile */

        $user = Yii::$app->getModule("user")->model("User");
        $user->setScenario("admin");
        $profile = Yii::$app->getModule("user")->model("Profile");

        $post = Yii::$app->request->post();
        if ($user->load($post) && $user->validate() && $profile->load($post) && $profile->validate()) {
            $user->save(false);
            $profile->setUser($user->id)->save(false);
            return $this->redirect(['view', 'id' => $user->id]);
        }

        /** templates for select2 */
        $user->templates = ArrayHelper::map(Template::find()->where(['status' => Template::STATUS_ACTIVE])->all(), 'id', 'title');

        /** subscriptions for select2 */
        $user->subscriptions = ArrayHelper::map(Subscription::find()->where(['status' => Template::STATUS_ACTIVE])->all(), 'id', 'name');

        if ($currentUserSubscription = SubscriptionUserAssignment::getUserActiveSubscription($user->id)) {
            $user->subscriptionId = $currentUserSubscription->subscription_id;
        }

        if ($bespokenTemplate = Yii::$app->request->getQueryParam('bespokenTemplate', null)) {
            $user->bespokenTemplate = $bespokenTemplate;
        }

        // render
        return $this->render('create', [
            'user' => $user,
            'profile' => $profile,
        ]);
    }

    /**
     * Update an existing User model. If update is successful, the browser
     * will be redirected to the 'view' page.
     *
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        // set up user and profile
        $user = $this->findModel($id);
        $user->setScenario("admin");
        $profile = $user->profile;

        // load post data and validate
        $post = Yii::$app->request->post();
        if ($user->load($post) && $user->validate() && $profile->load($post) && $profile->validate()) {
            $user->save(false);
            $profile->setUser($user->id)->save(false);
            return $this->redirect(['view', 'id' => $user->id]);
        }

        /** templates for select2 */
        $user->templates = ArrayHelper::map(Template::find()->where(['status' => Template::STATUS_ACTIVE])->all(), 'id', 'title');

        /** subscriptions for select2 */
        $user->subscriptions = ArrayHelper::map(Subscription::find()->where(['status' => Template::STATUS_ACTIVE])->all(), 'id', 'name');

        if ($currentUserSubscription = SubscriptionUserAssignment::getUserActiveSubscription($user->id)) {
            $user->subscriptionId = $currentUserSubscription->subscription_id;
        }

        // render
        return $this->render('update', [
            'user' => $user,
            'profile' => $profile,
        ]);
    }

    /**
     * List all User models
     *
     * @return mixed
     */
    public function actionIndex()
    {
        /** @var \amnah\yii2\user\models\search\UserSearch $searchModel */
        $searchModel = Yii::$app->getModule("user")->model("UserSearch");
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    protected function findModel($id)
    {
        /** @var \amnah\yii2\user\models\User $user */
        $user = new \backend\models\User;
        if (($user = $user::findOne($id)) !== null) {
            return $user;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/template/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\models\Mediafile;
use backend\widgets\FileInput;
use backend\assets\HtmlSortableAsset;
use kartik\select2\Select2;
use common\models\Template;

HtmlSortableAsset::register($this);
/* @var $this yii\web\View */
/* @var $model common\models\Template */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="template-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model) ?>

    <div class="form-group clearfix">
        <div class="col-sm-4">
            <?= $form->field($model, 'title')->textInput(['maxlength' => 150]) ?>
            <?= $form->field($model, 'type')->dropDownList(Template::$types) ?>
            <?= $form->field($model, 'comment')->textarea(['maxlength' => 255]) ?>
            <?= $form->field($model, 'status')->radioList(['disabled' => 'Disabled', 'active' => 'Active',], ['unselect' => 'active']) ?>
        </div>

        <div class="col-sm-8">
            <?= $form->field($model, 'html')->textarea(['rows' => 3]) ?>
            <?= $form->field($model, 'css')->textarea(['rows' => 3]) ?>

            <?= Select2::widget([
                'name' => 'scripts-select',
                'value' => '',
                'data' => $model->scripts,
                'options' => [
                    'placeholder' => 'Add a script...',
                ],
                'pluginOptions' => [
                    'allowClear' => true
                ],
                'pluginEvents' => [
                    "change" => 'function(e) { raconteur.addScript(this,"Template[scriptIds][]");}',
                ]
            ]); ?>

            <ul class="scripts-sortable" data-target="template-scriptids">
                <?php
                if ($scriptsAssigned = $model->scriptTemplateAssignments) {
                    foreach ($scriptsAssigned as $sa) {
                        ?>
                        <li>
                            <?= $model->scripts[$sa->script_id] ?>
                            <input type="hidden" value="<?= $sa->script_id ?>" name="Template[scriptIds][]">
                            <span class="remove">x</span>
                        </li>
                    <?php
                    }
                }
                ?>
            </ul>

        </div>
    </div>

    <hr>

    <div class="form-group clearfix">

        <?= $form->field($model, 'preview_img')->hiddenInput() ?>

        <div class="col-sm-4">
            <?php
            echo FileInput::widget([
                'name' => 'template-preview',
                'buttonTag' => 'button',
                'buttonName' => 'Browse',
                'buttonOptions' => ['class' => 'btn btn-info'],
                'options' => ['class' => 'hidden'],
                'ownerAttribute' => Mediafile::OWNER_ATTRIBUTE_ADMIN_IMG,
                'imageContainer' => '#template-preview-img',
                'template' => '<div class="input-group">{input}{button}</div>',
                'pasteData' => FileInput::DATA_URL,
                'callbackBeforeInsert' => 'function(e, data) {
                    $("input[name=\'Template[preview_img]\']").val(data.id);
                }',
            ]);
            ?>
        </div>
        <div class="col-sm-8" id="template-preview-img">
            <?php
            if ($model->previewImg) {
                echo Html::img($model->previewImg->defaultThumbUrl);
            }
            ?>
        </div>
    </div>

    <hr>

    <div class="form-group clearfix">
        <h5>Template images</h5>

        <div class="col-sm-4">
            <?= FileInput::widget([
                'name' => 'template-images',
                'buttonTag' => 'button',
                'buttonName' => 'Browse',
                'buttonOptions' => ['class' => 'btn btn-info'],
                'options' => ['class' => 'hidden'],
                'ownerAttribute' => Mediafile::OWNER_ATTRIBUTE_ADMIN_IMG,
                'template' => '<div class="input-group">{input}{button}</div>',
                'pasteData' => FileInput::DATA_URL,
                'callbackBeforeInsert' => 'function(e, data) { raconteur.addImage(data,"Template[imageIds][]");}',
            ]); ?>
        </div>

        <ul class="col-sm-8" id="images-assignments">
            <?php
            if ($imagesAssigned = $model->templateImageAssignments) {
                foreach ($imagesAssigned as $ia) {
                    $file = $ia->file;
                    ?>
                    <li>
                        <?= $file->name; ?>
                        <input type="hidden" value="<?= $ia->file_id ?>" name="Template[imageIds][]">
                        <button type="button" class="close remove" aria-label="Remove"><span
                                aria-hidden="true">&times;</span></button>
                    </li>
                <?php
                }
            }
            ?>
        </ul>
    </div>


    <hr>

    <div class="form-group clearfix">
        <h5>Template fonts</h5>

        <div class="col-sm-4">
            <?php /* FileInput::widget([
                'name' => 'template-fonts',
                'buttonTag' => 'button',
                'buttonName' => 'Browse',
                'buttonOptions' => ['class' => 'btn btn-info'],
                'options' => ['class' => 'hidden'],
                'ownerAttribute' => Mediafile::OWNER_ATTRIBUTE_ADMIN_FONT,
                'template' => '<div class="input-group">{input}{button}</div>',
                'pasteData' => FileInput::DATA_URL,
                'callbackBeforeInsert' => 'function(e, data) { raconteur.addFont(data,"Template[fontIds][]");}',
            ]); */ ?>
        </div>

        <ul class="col-sm-8" id="font-assignments">
            <?php
           /* if (false && $fontsAssigned = $model->templateFontAssignments) {
                foreach ($fontsAssigned as $fa) {
                    $file = $fa->file;
                    ?>
                    <li>
                        <?= Html::span($file->defaultThumbUrl); ?>
                        <input type="hidden" value="<?= $ia->file_id ?>" name="Template[fontIds][]">
                        <button type="button" class="close remove" aria-label="Remove">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </li>
                <?php
                }
            } */
            ?>
        </ul>
    </div>

    <hr>

    <?php if (!$model->isNewRecord) { ?>
        <div class="row updated">
            <div class="col-lg-12">
                Users : <?= $model->userTemplateAssignmentNumber; ?>&nbsp;
                <?= Html::a('Manage users', ['/user/admin', 'UserSearch[ids]' => $model->usersIdsAssignedToTemplate], ['class' => 'btn btn-warning btn-xs', 'target' => '_blank']) ?>
            </div>
        </div>

        <div class="row updated">
            <div class="col-lg-12">
                Sections : <?= $model->sectionsNumber ?>&nbsp;
                <?= Html::a('Manage sections', ['/section/index', 'SectionSearch[template_id]' => $model->id], ['class' => 'btn btn-warning btn-xs', 'target' => '_blank']) ?>
            </div>
        </div>

        <?= Html::a('Assign template to a new user', ['/admin/create', 'bespokenTemplate' => $model->id], ['class' => 'btn btn-success btn-xs', 'target' => '_blank']) ?>
    <?php } ?>

    <br/>
    <br/>
    <hr>

    <div class="form-group clearfix">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

        <?= Html::a('Cansel', ['index'], ['class' => 'btn btn-warning']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/template/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\TemplateSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="template-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'comment') ?>

    <?= $form->field($model, 'preview_img') ?>

    <?= $form->field($model, 'html') ?>

    <?php // echo $form->field($model, 'css') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'created') ?>

    <?php // echo $form->field($model, 'modified') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/template/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Template */

$this->title = 'Create Template';
$this->params['breadcrumbs'][] = ['label' => 'Templates', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="template-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model
    ]) ?>

</div>

backend/views/template/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\TemplateSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Templates';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="template-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Template', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,

        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'id',
                'headerOptions' => ['style' => 'width: 80px;'],
            ],
            'title',
            'status',
            [
                'attribute' => 'sectionsNumber',
                'header' => 'Sections',
                'headerOptions' => ['style' => 'width: 80px;'],
            ],
            [
                'format' => 'image',
                'value' => function ($data) {
                    if ($image = $data->previewImageModel) {
                        return $image->defaultThumbUrl;
                    }
                },
                'header' => 'Image Preview',
                'headerOptions' => ['style' => 'width: 128px;'],
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'headerOptions' => ['style' => 'width: 70px;'],
                'buttons' => [
                    'delete' => function ($url, $model, $key) {
                        $confirmMsg = Yii::t('yii', 'Are you sure you want to delete this item?');

                        $subscriptions = count($model->subscriptions);
                        $assignedToUsers = count($model->users);
                        $assignedSections = $model->sectionsNumber;

                        if ($subscriptions + $assignedToUsers + $assignedSections > 0) {
                            $url = '#';
                            $confirmMsg = "Sorry, this template can't be deleted because: \r\n";

                            if($subscriptions>0){
                                $confirmMsg.="\r\nIt's using by $subscriptions subscription(s)";
                            }

                            if($assignedToUsers>0){
                                $confirmMsg.="\r\nIt's assigned to $assignedToUsers user(s)";
                            }

                            if($assignedSections>0){
                                $confirmMsg.="\r\nIt has $assignedSections section(s)";
                            }

                            $confirmMsg.="\r\n\r\nPlease consider to delete them or their relationships at first.";
                        }
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'title' => Yii::t('yii', 'Delete'),
                            'data-confirm' => $confirmMsg,
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ]);
                    }
                ]
            ],
        ],
    ]); ?>

</div>

backend/views/template/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Template */

$this->title = 'Update Template: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Templates', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="template-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model
    ]) ?>

</div>

backend/views/template/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Menu;

use backend\assets\HighlightjsAsset;

HighlightjsAsset::register($this);

/* @var $this yii\web\View */
/* @var $model common\models\Template */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Templates', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="template-view">
    <div class="container">
        <div class="row">

            <div class="col-lg-4">
                <h4><?= $model->title; ?></h4>
                <figure class="default-template-preview">
                    <?php if ($model->preview_img) {
                        echo Html::img($model->previewImg->thumbs['medium']);
                    } ?>
                </figure>
            </div>

            <div class="col-lg-6">
                <section class="row">
                    <h4>Type: <?= $model->type; ?></h4>

                </section>
                <section class="row">
                    <h4>Comments</h4>
                    <?= $model->comment; ?>
                </section>
                <section class="row">
                    <h4>HTML</h4>
                    <pre><code class="html"><?= $model->html; ?></code></pre>
                </section>
                <section class="row">
                    <h4>CSS</h4>
                    <pre><code class="css"><?= $model->css; ?></code></pre>
                </section>
                <section class="row">
                    <h4>Scripts</h4>
                    <ul>
                        <?php
                        if ($scriptsAssigned = $model->scriptTemplateAssignments) {
                            foreach ($scriptsAssigned as $sa) {
                                ?>
                                <li>
                                    <?= $model->scripts[$sa->script_id] ?>
                                </li>
                            <?php
                            }
                        }
                        ?>
                    </ul>
                </section>
            </div>
        </div>

        <div class="section-to-template">

            <?php $sectionAssigned = $model->sectionsAssigned; ?>
            <h2>
                Sections: <?= $model->sectionsNumber ?>&nbsp;
                <?= Html::a('Manage sections', ['/section/index', 'SectionSearch[template_id]' => $model->id], ['class' => 'btn btn-warning btn-xs']) ?>
            </h2>

            <ul class="col-lg-8 simple-list" id="section-assignments">
                <?php
                if ($sectionAssigned = $model->sectionsAssigned) {
                    foreach ($sectionAssigned as $ia) {
                        ?>
                        <li>
                            <div class="row">
                                <div class="col-lg-1">
                                    <figure class="list-image-preview">
                                        <?php if ($ia->previewImageModel): ?>
                                            <?= Html::img($ia->previewImageModel->defaultThumbUrl); ?>
                                        <?php endif ?>
                                    </figure>
                                </div>
                                <div class="col-lg-5"><?= Html::a($ia['title'], ['/section/update', 'id' => $ia['id']]); ?> </div>
                            </div>
                        </li>
                    <?php
                    }
                }
                ?>
            </ul>
        </div>

        <br/>
        <br/>
        <br/>

        <div class="row  updated">
            <div class="col-lg-12">Last updated : <?= date("F j, Y H:i", $model->modified); ?></div>
        </div>
        <div class="row updated">
            <div class="col-lg-12">
                Assigned to users : <?= $model->userTemplateAssignmentNumber; ?>&nbsp;
                <?= Html::a('Manage users', ['/user/admin', 'UserSearch[ids]' => $model->usersIdsAssignedToTemplate], ['class' => 'btn btn-warning btn-xs']) ?>
            </div>
        </div>


    </div>

    <br/>


    <div class="form-group clearfix">
        <div class="col-xs-12">
            <?= Html::a('Back to templates', ['index', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Edit template', ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        </div>
    </div>
</div>