backend/controllers/RequestController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\UserRequest;
use common\models\search\UserRequestSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * RequestController implements the CRUD actions for UserRequest model.
 */
class RequestController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all UserRequest models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserRequestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UserRequest model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UserRequest model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserRequest();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing UserRequest model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing UserRequest model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the UserRequest model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserRequest the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserRequest::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/admin/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use api\modules\v1\models\Mediafile;
use backend\widgets\FileInput;

$role = Yii::$app->getModule("user")->model("Role");

/**
 * @var yii\web\View $this
 * @var amnah\yii2\user\models\User $user
 * @var amnah\yii2\user\models\Profile $profile
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary([$user, $profile]) ?>

    <div class="form-group clearfix">
        <div class="col-sm-4">
            <?= $form->field($user, 'username')->textInput(['maxlength' => 255]) ?>
            <?= $form->field($user, 'newPassword')->passwordInput() ?>
            <?= $form->field($user, 'email')->textInput(['maxlength' => 255]) ?>
            <?= $form->field($profile, 'first_name'); ?>
            <?= $form->field($profile, 'last_name'); ?>
            <?= $form->field($profile, 'company'); ?>
            <?= $form->field($profile, 'position'); ?>

            <?= FileInput::widget([
                'name' => 'section-images',
                'buttonTag' => 'button',
                'buttonName' => 'User Files',
                'buttonOptions' => ['class' => 'btn btn-info btn-sm'],
                'options' => ['class' => 'hidden'],
                'ownerAttribute' => Mediafile::OWNER_ATTRIBUTE_FILE_FROM_THIRD_APP,
                'ownerId' => $user->id,
                'template' => '<div class="input-group">{input}{button}</div>',
                'pasteData' => FileInput::DATA_URL,
            ]); ?>
        </div>
        <div class="col-sm-4">

            <!--Subscription-->
            <?= $form->field($user, 'subscriptionId')->widget(Select2::classname(), [
                'data' => $user->subscriptions,
                'options' => [
                    'placeholder' => 'Choose a subscription...',
                ],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>

            <!--Assigned Templates-->
            <div class="form-group">
                <label class="control-label" for="user-subscriptionid">Template</label>
                <?= Select2::widget([
                    'name' => 'templates-select',
                    'value' => '',
                    'data' => $user->templates,
                    'options' => [
                        'placeholder' => 'Add a template...',
                    ],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                    'pluginEvents' => [
                        "change" => 'function(e) { raconteur.addTemplate(this,"User[templateIds][]");}',
                    ]
                ]); ?>
                <ul class="model-templates">
                    <?php
                    if ($templatesAssigned = $user->userTemplateAssignments) {
                        foreach ($templatesAssigned as $ta) {
                            if(isset($user->templates[$ta->template_id])){
                                ?>
                                <li>
                                    <?= $user->templates[$ta->template_id] ?>
                                    <input type="hidden" value="<?= $ta->template_id ?>" name="User[templateIds][]">
                                    <span class="remove">x</span>
                                </li>
                            <?php
                            }
                        }
                    }
                    if ($user->bespokenTemplate) {
                        ?>
                        <li>
                            <?= $user->templates[$user->bespokenTemplate] ?>
                            <input type="hidden" value="<?= $user->bespokenTemplate ?>" name="User[templateIds][]">
                            <span class="remove">x</span>
                        </li>
                    <?php
                    }
                    ?>
                </ul>
            </div>

            <?= $form->field($user, 'role_id')->dropDownList($role::dropdown(), ['prompt' => 'Choose...']); ?>

            <?= $form->field($user, 'status')->dropDownList($user::statusDropdown()); ?>

            <?= $form->field($profile, 'phone'); ?>

        </div>
    </div>

    <hr>

    <div class="form-group">
        <div class="col-sm-12">
            <?= Html::submitButton($user->isNewRecord ? 'Create' : 'Update', ['class' => $user->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            <?= Html::a('Cansel', ['index'], ['class' => 'btn btn-warning']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/admin/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var amnah\yii2\user\models\search\UserSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'role_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'new_email') ?>

    <?php // echo $form->field($model, 'username') ?>

    <?php // echo $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'api_key') ?>

    <?php // echo $form->field($model, 'login_ip') ?>

    <?php // echo $form->field($model, 'login_time') ?>

    <?php // echo $form->field($model, 'create_ip') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'update_time') ?>

    <?php // echo $form->field($model, 'ban_time') ?>

    <?php // echo $form->field($model, 'ban_reason') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('user', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('user', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/admin/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var amnah\yii2\user\models\User $user
 * @var amnah\yii2\user\models\Profile $profile
 */

$this->title = Yii::t('user', 'Create {modelClass}', [
  'modelClass' => 'User',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'user' => $user,
        'profile' => $profile,
    ]) ?>

</div>

backend/views/admin/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use \common\models\SubscriptionUserAssignment;

$user = Yii::$app->getModule("user")->model("User");
$role = Yii::$app->getModule("user")->model("Role");

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var amnah\yii2\user\models\search\UserSearch $searchModel
 * @var amnah\yii2\user\models\User $user
 * @var amnah\yii2\user\models\Role $role
 */

$this->title = Yii::t('user', 'Users');
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => 'index'];
?>
<div class="user-index">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('user', 'Create {modelClass}', [
            'modelClass' => 'User',
        ]), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'id',
                'headerOptions' => ['style' => 'width: 80px;'],
            ],
            'username',
            'email:email',
            'profile.company',
            [
                'attribute' => 'status',
                'label' => Yii::t('user', 'Status'),
                'filter' => $user::statusDropdown(),
                'value' => function ($model, $index, $dataColumn) use ($user) {
                    $statusDropdown = $user::statusDropdown();
                    return $statusDropdown[$model->status];
                },
            ],
            [
                'header' => 'Status',
                'format' => 'html',
                'value' => function ($data) {
                    $subscription = $data->getSubscriptionUserAssignment([SubscriptionUserAssignment::STATUS_ACTIVE])->one();
                    if ($subscription) {
                        $data->activeSubscription = $subscription;
                        return "expires on<br>" . date('Y-m-d H:i', $subscription->end_date);
                    }
                }
            ],
            'login_time',
            [
                'header' => '#saved',
                'value' => function ($data) {
                    if ($data->activeSubscription) {
                        return $data->activeSubscription->pages_saved . "/" . $data->activeSubscription->subscription->pages_allowed;
                    }
                }
            ],
            [
                'header' => '#downloads',
                'value' => function ($data) {
                    if ($data->activeSubscription) {
                        return $data->activeSubscription->downloads . "/" . $data->activeSubscription->subscription->downloads_allowed;
                    }
                }
            ],
            [
                'header' => '#published',
                'value' => function ($data) {
                    if ($data->activeSubscription) {
                        return $data->activeSubscription->pages_published . "/" . $data->activeSubscription->subscription->publishes_allowed;
                    }
                }
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/admin/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var amnah\yii2\user\models\User $user
 * @var amnah\yii2\user\models\Profile $profile
 */

$fullName = $user->profile['first_name'] . ' ' . $user->profile['last_name'];

$this->title = Yii::t('user', 'Update {modelClass}: ', ['modelClass' => 'User',]) . ' ' . $fullName;

$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $fullName, 'url' => ['view', 'id' => $user->id]];
$this->params['breadcrumbs'][] = Yii::t('user', 'Update');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'user' => $user,
        'profile' => $profile,
    ]) ?>

</div>

backend/views/admin/view.php
<?php

use yii\helpers\Html;
use \common\models\SubscriptionUserAssignment;
use api\modules\v1\models\Mediafile;
use backend\widgets\FileInput;

/**
 * @var yii\web\View $this
 * @var amnah\yii2\user\models\User $user
 * @var amnah\yii2\user\models\Profile $profile
 * @var yii\widgets\ActiveForm $form
 */

$this->title = $user->profile['first_name'] . ' ' . $user->profile['last_name'];
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">
    <div class="container">

        <div class="row">
            <div class="col-md-4">
                <?php
                if (is_numeric($user->profile->photo)) {
                    $photo = Mediafile::findOne($user->profile->photo);
                    if ($photo) {
                        echo  Html::img($photo->defaultThumbUrl);
                    }
                }
                ?>
                <div style="color:#0088CC"><?= Html::encode($this->title) ?><?= $user->profile['company'] ? ', ' . $user->profile['company'] : '' ?></div>


            </div>
            <?php
            $subscription = $user->getSubscriptionUserAssignment([SubscriptionUserAssignment::STATUS_ACTIVE])->one();
            $user->activeSubscription = $subscription;
            if ($subscription) {
                ?>

                <div class="col-md-4">
                    <span>Subscription: <?= $user->activeSubscription->subscription->name; ?></span>

                </div>

                <div class="col-md-4">
                    <?= "Subscription Expires on " . date('Y-m-d H:i', $subscription->end_date) ?>
                </div>
            <?php } ?>
        </div>

        <div class="row user-personal-data">
            <div class="col-lg-4">
                <h4>Personal data</h4>

                <div class="tbl">
                    <div class="tbl-tow">
                        <div class="tbl-cell">Company:</div>
                        <div class="tbl-cell"><?= $user->profile['company']; ?></div>
                    </div>
                    <div class="tbl-tow">
                        <div class="tbl-cell">Position:</div>
                        <div class="tbl-cell"><?= $user->profile['position']; ?></div>
                    </div>
                    <div class="tbl-tow">
                        <div class="tbl-cell">Email:</div>
                        <div class="tbl-cell"><?= $user->email; ?></div>
                    </div>
                    <div class="tbl-tow">
                        <div class="tbl-cell">Phone:</div>
                        <div class="tbl-cell"><?= $user->profile['phone']; ?></div>
                    </div>
                </div>
            </div>

            <?php if ($requests = $user->userRequests) { ?>
                <div class="col-lg-8">
                    <h4>Requests from user</h4>

                    <ul>
                        <?php foreach ($requests as $request) { ?>
                            <li><?= Html::a(date('Y-m-d H:i', $request->created) . ' ' . @\common\models\UserRequest::$types[$request->type] . " ({$request->status})", ['/request/view', 'id' => $request->id]) ?></li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>

        </div>


        <section class="user-activity-data">
            <h4>Activity</h4>
            <ul class="model-templates" style="width: 200px">
                <?php
                if ($templatesAssigned = $user->userTemplateAssignments) {
                    foreach ($templatesAssigned as $ta) {
                        if (isset($user->templates[$ta->template_id])) {
                            ?>
                            <li>
                                <?= Html::a($user->templates[$ta->template_id], ['/template/view', 'id' => $ta->template_id]) ?>
                            </li>
                        <?php
                        }
                    }
                }
                ?>
            </ul>
        </section>

        <div class="row">
            <div class="col-lg-10">
                <?= FileInput::widget([
                    'name' => 'section-images',
                    'buttonTag' => 'button',
                    'buttonName' => 'User Files',
                    'buttonOptions' => ['class' => 'btn btn-info btn-sm'],
                    'options' => ['class' => 'hidden'],
                    'ownerAttribute' => Mediafile::OWNER_ATTRIBUTE_FILE_FROM_THIRD_APP,
                    'ownerId' => $user->id,
                    'template' => '<div class="input-group">{input}{button}</div>',
                    'pasteData' => FileInput::DATA_URL,
                ]); ?>
            </div>
        </div>
        <br/>

        <div class="row">
            <div class="col-lg-10">
                Last login : <?= $user->login_time; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10">
                Sessions : <?= $user->profile['sessions']; ?>
            </div>
        </div>

    </div>

    <!--Buttons-->
    <div class="mar-tb-10">
        <div class="col-xs-12">
            <?= Html::a('Back to users', ['/user/admin',], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Edit user', ['user/admin/update', 'id' => $user->id], ['class' => 'btn btn-success']) ?>
        </div>
    </div>

</div>